#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom cli cli_abort
#' @importFrom cli cli_alert_info
#' @importFrom cli cli_alert_success
#' @importFrom cli cli_end
#' @importFrom cli cli_h1
#' @importFrom cli cli_li
#' @importFrom cli cli_progress_done
#' @importFrom cli cli_progress_step
#' @importFrom cli cli_rule
#' @importFrom cli cli_text
#' @importFrom cli cli_ul
#' @importFrom colorspace darken
#' @importFrom colorspace lighten
#' @importFrom dplyr across
#' @importFrom dplyr all_of
#' @importFrom dplyr case_when
#' @importFrom dplyr distinct
#' @importFrom dplyr filter
#' @importFrom dplyr if_else
#' @importFrom dplyr join_by
#' @importFrom dplyr left_join
#' @importFrom dplyr lst
#' @importFrom dplyr matches
#' @importFrom dplyr mutate
#' @importFrom dplyr na_if
#' @importFrom dplyr pull
#' @importFrom dplyr relocate
#' @importFrom dplyr rename
#' @importFrom dplyr rename_with
#' @importFrom dplyr select
#' @importFrom dplyr where
#' @importFrom ggplot2 %+replace%
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 after_scale
#' @importFrom ggplot2 after_stat
#' @importFrom ggplot2 element_blank
#' @importFrom ggplot2 element_line
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 geom_bar
#' @importFrom ggplot2 geom_text
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 ggsave
#' @importFrom ggplot2 is.ggplot
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 margin
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 unit
#' @importFrom ggplot2 waiver
#' @importFrom ggtext element_markdown
#' @importFrom ggtext element_textbox
#' @importFrom glue glue
#' @importFrom grid rasterGrob
#' @importFrom gt cell_borders
#' @importFrom gt cell_text
#' @importFrom gt cells_body
#' @importFrom gt cells_column_labels
#' @importFrom gt cells_stub
#' @importFrom gt cells_stubhead
#' @importFrom gt data_color
#' @importFrom gt gt
#' @importFrom gt gtsave
#' @importFrom gt opt_table_font
#' @importFrom gt px
#' @importFrom gt sub_missing
#' @importFrom gt tab_options
#' @importFrom gt tab_style
#' @importFrom gtsummary as_gt
#' @importFrom htmltools capturePlot
#' @importFrom labelled generate_dictionary
#' @importFrom labelled var_label
#' @importFrom magrittr %>%
#' @importFrom png readPNG
#' @importFrom purrr list_c
#' @importFrom purrr list_flatten
#' @importFrom purrr list_modify
#' @importFrom purrr map
#' @importFrom purrr map2
#' @importFrom purrr reduce
#' @importFrom rlang :=
#' @importFrom rlang enexpr
#' @importFrom rlang enexprs
#' @importFrom rlang env
#' @importFrom rlang expr
#' @importFrom rlang exprs
#' @importFrom rlang set_names
#' @importFrom scales percent
#' @importFrom stats na.omit
#' @importFrom stats reformulate
#' @importFrom stringr str_detect
#' @importFrom stringr str_extract
#' @importFrom stringr str_flatten_comma
#' @importFrom stringr str_remove
#' @importFrom stringr str_starts
#' @importFrom systemfonts system_fonts
#' @importFrom tibble tibble
#' @importFrom utils browseURL
#' @importFrom webshot webshot
## usethis namespace: end
NULL
