#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom cli cli_abort
#' @importFrom cli cli_alert_info
#' @importFrom cli cli_alert_success
#' @importFrom cli cli_end
#' @importFrom cli cli_h1
#' @importFrom cli cli_li
#' @importFrom cli cli_progress_done
#' @importFrom cli cli_progress_step
#' @importFrom cli cli_rule
#' @importFrom cli cli_text
#' @importFrom cli cli_ul
#' @importFrom colorspace darken
#' @importFrom colorspace lighten
#' @importFrom dplyr all_of
#' @importFrom dplyr distinct
#' @importFrom dplyr filter
#' @importFrom dplyr lst
#' @importFrom dplyr matches
#' @importFrom dplyr mutate
#' @importFrom dplyr pull
#' @importFrom dplyr relocate
#' @importFrom dplyr rename_with
#' @importFrom dplyr select
#' @importFrom dplyr where
#' @importFrom ggplot2 %+replace%
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 after_scale
#' @importFrom ggplot2 after_stat
#' @importFrom ggplot2 geom_bar
#' @importFrom ggplot2 geom_text
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 ggsave
#' @importFrom ggplot2 is.ggplot
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 waiver
#' @importFrom glue glue
#' @importFrom gt gtsave
#' @importFrom gtsummary as_gt
#' @importFrom htmltools capturePlot
#' @importFrom labelled var_label
#' @importFrom magrittr %>%
#' @importFrom purrr list_c
#' @importFrom purrr list_modify
#' @importFrom purrr map
#' @importFrom purrr map2
#' @importFrom rlang :=
#' @importFrom rlang enexpr
#' @importFrom rlang env
#' @importFrom rlang expr
#' @importFrom rlang exprs
#' @importFrom rlang set_names
#' @importFrom scales percent
#' @importFrom stats na.omit
#' @importFrom stats reformulate
#' @importFrom stringr str_detect
#' @importFrom stringr str_extract
#' @importFrom stringr str_flatten_comma
#' @importFrom stringr str_remove
#' @importFrom stringr str_starts
#' @importFrom systemfonts system_fonts
#' @importFrom utils browseURL
#' @importFrom webshot webshot
## usethis namespace: end
NULL
