#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom broom tidy
#' @importFrom broom.helpers model_list_terms_levels
#' @importFrom cli cli_abort
#' @importFrom cli cli_alert_info
#' @importFrom cli cli_alert_success
#' @importFrom cli cli_end
#' @importFrom cli cli_h1
#' @importFrom cli cli_li
#' @importFrom cli cli_progress_done
#' @importFrom cli cli_progress_step
#' @importFrom cli cli_rule
#' @importFrom cli cli_text
#' @importFrom cli cli_ul
#' @importFrom colorspace darken
#' @importFrom colorspace lighten
#' @importFrom dplyr across
#' @importFrom dplyr all_of
#' @importFrom dplyr arrange
#' @importFrom dplyr case_when
#' @importFrom dplyr desc
#' @importFrom dplyr distinct
#' @importFrom dplyr filter
#' @importFrom dplyr group_by
#' @importFrom dplyr if_else
#' @importFrom dplyr join_by
#' @importFrom dplyr left_join
#' @importFrom dplyr lst
#' @importFrom dplyr matches
#' @importFrom dplyr mutate
#' @importFrom dplyr na_if
#' @importFrom dplyr pull
#' @importFrom dplyr relocate
#' @importFrom dplyr rename
#' @importFrom dplyr rename_with
#' @importFrom dplyr rowwise
#' @importFrom dplyr select
#' @importFrom dplyr ungroup
#' @importFrom dplyr where
#' @importFrom ggplot2 %+replace%
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 after_scale
#' @importFrom ggplot2 after_stat
#' @importFrom ggplot2 element_blank
#' @importFrom ggplot2 element_line
#' @importFrom ggplot2 element_rect
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 geom_bar
#' @importFrom ggplot2 geom_text
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 ggsave
#' @importFrom ggplot2 is.ggplot
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 margin
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 theme_classic
#' @importFrom ggplot2 theme_void
#' @importFrom ggplot2 unit
#' @importFrom ggplot2 waiver
#' @importFrom ggsurvfit theme_risktable_default
#' @importFrom ggtext element_markdown
#' @importFrom ggtext element_textbox
#' @importFrom glue glue
#' @importFrom grid rasterGrob
#' @importFrom gt cell_borders
#' @importFrom gt cell_text
#' @importFrom gt cells_body
#' @importFrom gt cells_column_labels
#' @importFrom gt cells_footnotes
#' @importFrom gt cells_stub
#' @importFrom gt cells_stubhead
#' @importFrom gt cells_title
#' @importFrom gt data_color
#' @importFrom gt fmt_number
#' @importFrom gt gt
#' @importFrom gt gtsave
#' @importFrom gt md
#' @importFrom gt opt_align_table_header
#' @importFrom gt opt_table_font
#' @importFrom gt pct
#' @importFrom gt px
#' @importFrom gt sub_missing
#' @importFrom gt tab_footnote
#' @importFrom gt tab_header
#' @importFrom gt tab_options
#' @importFrom gt tab_style
#' @importFrom gtsummary add_overall
#' @importFrom gtsummary as_gt
#' @importFrom gtsummary bold_p
#' @importFrom gtsummary label_style_pvalue
#' @importFrom gtsummary modify_column_indent
#' @importFrom gtsummary modify_footnote
#' @importFrom gtsummary modify_header
#' @importFrom gtsummary modify_spanning_header
#' @importFrom gtsummary modify_table_body
#' @importFrom gtsummary modify_table_styling
#' @importFrom gtsummary reset_gtsummary_theme
#' @importFrom gtsummary style_percent
#' @importFrom gtsummary style_pvalue
#' @importFrom gtsummary theme_gtsummary_language
#' @importFrom htmltools capturePlot
#' @importFrom labelled generate_dictionary
#' @importFrom labelled label_attribute
#' @importFrom labelled var_label
#' @importFrom magick image_read_svg
#' @importFrom magick image_write
#' @importFrom magrittr %>%
#' @importFrom png readPNG
#' @importFrom purrr accumulate
#' @importFrom purrr list_c
#' @importFrom purrr list_flatten
#' @importFrom purrr list_modify
#' @importFrom purrr map
#' @importFrom purrr map_int
#' @importFrom purrr map2
#' @importFrom purrr reduce
#' @importFrom rlang :=
#' @importFrom rlang check_dots_empty
#' @importFrom rlang enexpr
#' @importFrom rlang enexprs
#' @importFrom rlang env
#' @importFrom rlang expr
#' @importFrom rlang exprs
#' @importFrom rlang inject
#' @importFrom rlang is_named
#' @importFrom rlang list2
#' @importFrom rlang set_names
#' @importFrom scales label_percent
#' @importFrom scales percent
#' @importFrom stats na.omit
#' @importFrom stats reformulate
#' @importFrom stringr regex
#' @importFrom stringr str_c
#' @importFrom stringr str_detect
#' @importFrom stringr str_extract
#' @importFrom stringr str_flatten_comma
#' @importFrom stringr str_remove
#' @importFrom stringr str_remove_all
#' @importFrom stringr str_replace
#' @importFrom stringr str_replace_all
#' @importFrom stringr str_starts
#' @importFrom stringr str_subset
#' @importFrom systemfonts system_fonts
#' @importFrom tibble add_row
#' @importFrom tibble tibble
#' @importFrom tidyr pivot_longer
#' @importFrom tidyr separate_longer_delim
#' @importFrom tidyr unnest
#' @importFrom utils browseURL
#' @importFrom webshot webshot
## usethis namespace: end
NULL
